# -*- coding: utf-8 -*-
"""To-Do List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLPrfCyJo4nagJvn1Xs7tqTzpS4252Ey
"""

# To-Do List Project
tasks = []

while True:
    print("\n===== TO-DO LIST =====")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Exit")

    choice = input("Enter your choice (1-3): ")

    if choice == "1":
        task = input("Enter a new task: ")
        tasks.append(task)
        print("✅ Task added successfully!")

    elif choice == "2":
        if len(tasks) == 0:
            print("📭 No tasks available.")
        else:
            print("\n📋 Your Tasks:")
            for i, task in enumerate(tasks, start=1):
                print(f"{i}. {task}")

    elif choice == "3":
        print("👋 Thank you!")
        break

    else:
        print("❌ Invalid choice. Please try again.")